---
abstract: 'Check whether an address looks like a P.O.Box'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-Address-POBox
provides:
  Business::Address::POBox:
    file: lib/Business/Address/POBox.pm
    version: 1.100820
requires:
  Carp: 0
  Class::Accessor::Complex: 0
  Class::Accessor::Constructor: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  String::BlackWhiteList: 0
  Test::Exception: 0
  Test::More: 0.88
  constant: 0
  parent: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Business-Address-POBox
  homepage: http://search.cpan.org/dist/Business-Address-POBox/
  repository: http://github.com/hanekomu/Business-Address-POBox
version: 1.100820
